### ISSUE TITLE
mailchimp signup forms not working on Ubuntu Chrome/Firefox

### ISSUE THREAD

**Issue by terrypearson** [brave/brave-website#40] opened 2016-02-01 20:07 UTC
I get random errors with the signup forms on both Chrome(48.0.2564.97) and Firefox (45.0b1), running Ubuntu 15.10. 

On Chrome, I get an error like this :Cookie error Please make sure cookies are enabled. You may need to delete your cookies and try again.

This happens no matter what I do so I have no way to sign up.

**Comment by diracdeltas** [comment] 2016-02-01 23:51
duplicate of #29

**Comment by diracdeltas** [comment] 2016-02-02 00:37
fixed now

**Closed by diracdeltas** 2016-02-02 00:37 UTC
Labels: duplicate
